name: CI Tests

on:
  push:
    branches: [ main, master ]

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: false

      - name: upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: final-report 🧪
        run: npm run cypress:final-report

      - name: upload reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-reports
          path: mochawesome-report

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report        
